### ISSUE TITLE
run the Makefile have errors

### ISSUE THREAD

**Issue by Jiahua-Gong** [dovstamler/uvm_agents#3]
Hello ,,,
   I run the Makefile, meet some errors.I can't solve the problem. Can you help me?

TimeScale is 1 ns / 1 ns
VCS Coverage Metrics Release G-2012.09_Full64 Copyright (c) 1991-2012 by Synopsys Inc.
Starting vcs inline pass...
5 modules and 0 UDP read.
	However, due to incremental compilation, no re-compilation is necessary.
make[1]: Entering directory `/home/gongjh/uvm_test/csrc'
g++ -w  -pipe -DVCS -O -I/opt/synopsys/vcs201209/amd64/lib    -c ../../uvm-1.1d/src/dpi/uvm_dpi.cc
In file included from ../../uvm-1.1d/src/dpi/uvm_dpi.cc:35:
../../uvm-1.1d/src/dpi/uvm_hdl.c:23:22: error: veriuser.h: No such file or directory
make[1]: *** [uvm_dpi.o] Error 1
make[1]: Leaving directory `/home/gongjh/uvm_test/csrc'
Make exited with status 2
CPU time: 7.394 seconds to compile + .006 seconds to elab + .107 seconds to link
make: *** [comp] Error 2

**Comment by dovstamler** [comment]
Hi,
I'm not quite sure what the issues is but I would advise deleting all
intermediate files and directories created by the tools and then trying to
run again.

Dov

**Comment by dovstamler** [comment]
closed due to inactivity.
